events { worker_connections 1024; }

http {
    log_format upstreamlog '[$time_local] $remote_addr to: $upstream_addr: $request';

    upstream myapp {
        server web-app:80;
    }

    server {
        listen 80;
        access_log /var/log/nginx/access.log upstreamlog;

        location / {
            proxy_pass http://myapp;
            
            add_header X-Backend-Server $upstream_addr;
            # Baris ini wajib agar JavaScript bisa membaca header di atas
            add_header Access-Control-Expose-Headers "X-Backend-Server";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}